#+TITLE: Completion Configuration
#+AUTHOR: Chris Chambers
#+EMAIL: magma.chambers@gmail.com
#+LANGUAGE: en-gb
#+startup: align shrink inlineimages latexpreview content
#+property: header-args:elisp :results value silent

* Enable lexical binding
#+begin_src elisp
  ;; -*- lexical-binding: t -*-
#+end_src

* Basic Config
  #+begin_src elisp
    (use-package basic-completion
      :straight nil
      :no-require t
      :custom
      (completion-ignore-case t)
      (completion-styles '(flex basic)))
  #+end_src
* <<<corfu>>> ([[https://github.com/minad/corfu][github]])
  #+begin_src elisp
    (use-package corfu
      :init
      (global-corfu-mode)
      :custom
      (corfu-auto t)
      (corfu-auto-prefix 2)
      (tab-always-indent 'complete))
  #+end_src
** corfu-popupmenu
   #+begin_src elisp
     (use-package corfu-popupmenu
       :straight nil
       :no-require t
       :config
       (corfu-popupinfo-mode)
       :custom
       (corfu-popupinfo-delay '(0.5 . 0.2))
       (corfu-popupinfo--buffer-parameters
        '((truncate-partial-width-windows)
          (truncate-lines)
          ;; (top-margin-width . 2)
          ;; (bottom-margin-width . 2)
          (left-margin-width . 2)
          (right-margin-width . 2)
          (word-wrap . t)
          (fringe-indicator-alist
           (continuation)))))
   #+end_src
** cape
   #+begin_src elisp
     (use-package cape
       :bind (("C-x C-l" . cape-line)
       ))
   #+end_src

** COMMENT yasnippet-capf
#+begin_src elisp
  (use-package yasnippet-capf
    :straight (:host github :repo "elken/yasnippet-capf")
    :after cape
    ;; :config
    ;; (add-to-list 'completion-at-point-functions #'yasnippet-capf)
    )
#+end_src
** kind-icon
   #+begin_src elisp
     (use-package kind-icon
       :after corfu
       ;; :custom
       ;; (kind-icon-blend-background t)
       ;; (kind-icon-default-face 'corfu-default) ; only needed with blend-background
       :config
       (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
   #+end_src
* <<<vertico>>> ([[https://github.com/minad/vertico][github]])
  #+begin_src elisp
    (use-package vertico
      :init
      (vertico-mode)
      :hook
      (minibuffer-setup-hook . cursor-intangible-mode)
      :custom
      ;; Do not allow the cursor in the minibuffer prompt
      (minibuffer-prompt-properties
       '(read-only t cursor-intangible t face minibuffer-prompt))

      (vertico-cycle t)
      (completion-cycle-threshold 5)
      ;; default sort is: #'vertico-sort-history-length-alpha
      (vertico-sort-function #'vertico-sort-history-alpha)
      :general
      ('insert vertico-map
       "C-<return>"     #'vertico-exit-input ; though you should favour M-RET, that's the default
       "M-<tab>"        #'minibuffer-complete
       "C-o"            #'embark-export
       "C-."            #'embark-act
       "C-f"            #'vertico-scroll-up
       "C-b"            #'vertico-scroll-down
       "C-?"            #'minibuffer-completion-help
       "C-n"            #'next-line-or-history-element
       "C-p"            #'previous-line-or-history-element))
  #+end_src
** IN-PROGRESS Attempt at custom sorting function
   :LOGBOOK:
   - State "IN-PROGRESS" from "TODO"          [2024-01-14 Sun 21:28]
   :END:
   #+begin_src elisp
     (defun my/vertico--add-score-modifier (s user-input)
       (let* ((pattern (format "^%s$" user-input))
              (score-modifier
               (cond
                ((s-matches? pattern s)                       20) ; case-insensitive
                ((s-starts-with?  user-input s :ignore-case)  10)
                ((s-ends-with?    user-input s :ignore-case)  5)
                ((s-contains?     user-input s :ignore-case)  2)
                (:else 0))))
         (cons s score-modifier)))

     (defun my/vertico-sort-helper (candidates user-input)
       (if (not user-input)
           candidates
           (->> candidates
                (vertico-sort-history-length-alpha)
                (-map (-rpartial #'my/vertico--add-score-modifier user-input))
                ;; (-remove (-compose #'zerop #'cdr))
                (-sort (-on #'> #'cdr))
                (-map #'first))))

     (defun my/vertico-sort (candidates)
       (let ((user-input (minibuffer-contents)))
         (my/vertico-sort-helper candidates user-input)))
   #+end_src

*** COMMENT Testing
   #+begin_src elisp
     (-map (-rpartial #'my/vertico--add-score-modifier "an")
           '("apple" "aniseed" "nan" "an" "banana" "orange" "grape" "kiwi"))
   #+end_src

   #+begin_src elisp
       (my/vertico-sort-helper '("apple" "aniseed" "nan" "an" "banana" "orange" "grape" "kiwi") "a")
   #+end_src

   #+begin_src elisp
       (my/vertico-sort-helper '("apple" "aniseed" "nan" "an" "banana" "orange" "grape" "kiwi") "an")
   #+end_src

   #+begin_src elisp
     (let ((vertico-sort-function #'my/vertico-sort))
       (completing-read "Wibble: " '("apple" "aniseed" "nan" "an" "banana" "orange" "grape" "kiwi")))
   #+end_src

   #+begin_src elisp
     (-sort #'string<
       (-sort (-on #'< #'length)
              '("apple" "aniseed" "nan" "an" "banana" "orange" "grape" "kiwi")))
   #+end_src

*** COMMENT Enable
   #+begin_src elisp
     (customize-set-variable 'vertico-sort-function #'my/vertico-sort)
   #+end_src

*** Like, really enable. Really.
    Except in code-completion
    #+begin_src elisp
      (customize-set-variable 'vertico-sort-override-function #'my/vertico-sort)
    #+end_src

* COMMENT <<<orderless>>> ([[https://github.com/oantolin/orderless][github]])
  #+begin_quote
  The way completion styles work, when one style cannot match anything, Emacs
  tries the next one on the list, until one of them yields results. As such, it
  is easy to activate Orderless on demand, either by separating input groups
  with spaces or passing one of the style dispatchers that are acceptable

  -- Source: [[https://protesilaos.com/emacs/dotemacs#h:5c060e2e-231d-4896-a5d2-b3fb4134764e][GNU Emacs | Protesilaos Stavrou]]
  #+end_quote

  #+begin_important
  To open multiple files via globbing, you need:
  - partial-completion enabled, and
  - to move the cursor up to the minibuffer prompt (generally by pressing =C-p=)
    once you've written the glob expression
  #+end_important

  #+begin_src elisp
    (use-package orderless
      :preface
      (defun my/orderless-style-dispatcher-template (s delim symbol)
        (let ((n (->> s
                      (s-chop-suffix delim)
                      (s-chop-prefix delim))))
          (when (not (s-equals? n s))
            `(,symbol . ,n))))

      (defun literal-with-= (s _index _total)
        (my/orderless-style-dispatcher-template s "=" 'orderless-literal))

      (defun flex-with-~ (s _index _total)
        (my/orderless-style-dispatcher-template s "~" 'orderless-flex))

      (defun regexp-with-! (s _index _total)
        (my/orderless-style-dispatcher-template s "!" 'orderless-regexp))
      :custom
      (completion-styles '(partial-completion flex orderless))
      ;; (completion-styles '(flex orderless))
      (completion-ignore-case t)
      (completion-category-defaults nil)
      (orderless-component-separator "[ _-]+")
      (orderless-style-dispatchers '(literal-with-= flex-with-~ regexp-with-!))
      (orderless-matching-styles
       '(orderless-literal
         orderless-prefixes
         orderless-initialism
         orderless-regexp)))
  #+end_src

* COMMENT <<<embark>>> ([[https://github.com/oantolin/embark/][github]])
  #+begin_src elisp
    (use-package embark
      :config
      (advice-add 'embark-dwim  :around #'my/jump-advice)
      :general
      ('(motion normal)
       "C-]" 'embark-dwim ; override evil-jump-to-tag
       "M-." 'embark-dwim
       "C-." 'embark-act))
  #+end_src

** <<<embark-consult>>>
  #+begin_src elisp
    (use-package embark-consult)
  #+end_src

* COMMENT <<<consult>>> ([[https://github.com/minad/consult][github]])
  #+begin_quote
  Consult provides search and navigation commands based on the Emacs completion
  function src_elisp{(helpful-function #'completing-read)} . Completion allows
  you to quickly select an item from a list of candidates.

  [...]

  Some of the Consult commands are enhanced versions of built-in Emacs commands.
  For example the command consult-imenu presents a flat list of the Imenu with
  live preview, grouping and narrowing.
  #+end_quote

  If =persp-mode= is active, we use a different command for consult-buffer:
  (for dynamic-loading technique, see: [[https://stackoverflow.com/questions/7790382/how-to-determine-whether-a-package-is-installed-in-elisp][source]])

  #+begin_src elisp
    (if (require 'persp-mode nil 'noerror)
      (defun my/consult-buffer ()
        "`consult-buffer' with buffers provided by persp."
        (interactive)
        (with-persp-buffer-list ()
                                (consult-buffer)))
        (defun my/consult-buffer ()
          "`consult-buffer' wrapper."
          (interactive)
          (consult-buffer)))
  #+end_src

 #+begin_src elisp
   (use-package consult
     ;; :init
     ;; (fset 'multi-occur #'consult-multi-occur)
     :custom
     (consult-preview-key (list :debounce 0.5 'any))
     :config
     (setq consult-narrow-key "<")
     :general
     ;; ('(insert motion) "C-c C-o" 'consult-multi-occur)
     (leader
       "bB"   '(consult-buffer :which-key "switch buffer (all)")
       "bb"   '(my/consult-buffer :which-key "switch buffer (workspace)")

       "fr"   '(consult-recent-file :which-key "recent")
       "lk"   '(consult-yank-pop :which-key "kill-ring")
       "lr"   '(consult-register :which-key "register")
       "S"    '(:ignore t :which-key "search")
       "Sr"   '(consult-ripgrep :which-key "ripgrep")
       "Sg"   '(consult-git-grep :which-key "git-grep")
       "Sf"   '(consult-find :which-key "find")
       "Sl"   '(consult-locate :which-key "locate")

       "has"  '(consult-apropos :which-key "symbol")
       "."    '(consult-complex-command :which-key "repeat command")
       ))
 #+end_src

 #+begin_src elisp
   (with-eval-after-load
       'projectile 'consult
       (leader "pb" '(consult-project-buffer :which-key "switch buffer")))
 #+end_src

* COMMENT <<<marginalia>>> ([[https://github.com/minad/marginalia][github]])
  Adds annotations to completion candidates. Cannot change style of candidates
  themselves, just provides extra information. That extra information isn't able
  to be filtered via completing-read.

  #+begin_src elisp
    (use-package marginalia
      :config
      (marginalia-mode))
  #+end_src

** All-the-icons completion ([[https://github.com/iyefrat/all-the-icons-completion][source]])
   #+begin_src elisp
     (use-package all-the-icons-completion
       :hook (marginalia-mode . all-the-icons-completion-marginalia-setup))
   #+end_src

* COMMENT <<<company>>> ([[https://company-mode.github.io/][github]])/([[https://www.emacswiki.org/emacs/CompanyMode][wiki]])
  #+begin_src elisp
    (use-package company
      :preface
      (defun exit-company-normal-mode (&optional arguments)
	(interactive)
	(progn (company-abort) (evil-force-normal-state)))
      :demand t
      :custom
      (company-idle-delay 0.3)
      (company-minimum-prefix-length 2)
      :config
      (global-company-mode t)
      :general
      (:keymaps
       '(company-active-map company-search-map)
       "<escape>" 'exit-company-normal-mode
       "C-w"      'evil-delete-backward-word
       "C-j"      'company-select-next
       "C-k"      'company-select-previous
       "C-n"      'company-select-next
       "C-p"      'company-select-previous
       "C-l"      'company-complete-selection
       ;; "RET"      'company-complete-selection
       ;; "<tab>"    'company-complete-selection
       ;; "C-/"   'company-search-candidates
       "C-/"      'company-filter-candidates
       "C-h"      'company-show-doc-buffer)
      )

    (use-package company-box
      :hook (company-mode . company-box-mode))
  #+end_src

* COMMENT Vim-style line completion
  Source: [[https://www.emacswiki.org/emacs/HippieExpand][EmacsWiki: Hippie Expand]]
  Doesn't quite work.
  #+begin_src elisp
    ;; (general-define-key :prefix "C-x"
    ;;                     :states 'insert
    ;;                     "C-l"
    ;;                     (make-hippie-expand-function
    ;;                      '(try-expand-line try-expand-line-all-buffers)))

    (defun my/expand-lines ()
      (interactive)
      (let ((hippie-expand-try-functions-list
             '(try-expand-line try-expand-line-all-buffers)))
        (call-interactively 'hippie-expand)))

    (general-define-key :prefix "C-x"
                        :states 'insert
                        "C-l" #'my/expand-lines)
  #+end_src

* COMMENT <<<hotfuzz>>> ([[https://github.com/axelf4/hotfuzz][github]])
  A fuzzy-file matching like =flx=, but that has better sorting than the in-built
  =flex= matcher or =orderless-flex=.

  #+begin_src elisp
    (use-package hotfuzz
      :custom
      (completion-styles '(hotfuzz)))  ; incompatible with orderless, as always matches
  #+end_src

* COMMENT fussy
  #+begin_src elisp
    ;; (setq fussy-filter-fn 'fussy-filter-default)
    ;; (setq fussy-filter-fn 'fussy-filter-orderless)
    ;; (setq fussy-score-fn 'flx-score)
    ;; (setq fussy-default-regex-fn 'fussy-pattern-flex-2)
    (use-package orderless
      :ensure t)

    ;; (use-package flx-rs
    ;;   :straight (flx-rs :repo "jcs-elpa/flx-rs" :fetcher github :files (:defaults "bin"))
    ;;   :config
    ;;   (setq fussy-score-fn 'flx-rs-score)
    ;;   (flx-rs-load-dyn))

    (use-package fuz
      :straight (fuz :type git :host github :repo "rustify-emacs/fuz.el")
      :config
      (setq fussy-score-fn 'fussy-fuz-score)
      (unless (require 'fuz-core nil t)
        (fuz-build-and-load-dymod)))

    ;; (use-package liquidmetal
    ;;   :ensure t
    ;;   :straight t
    ;;   :config
    ;;   (setq fussy-score-fn 'fussy-liquidmetal-score))

    ;; (use-package fzf-native
    ;;   :ensure t
    ;;   :straight
    ;;   (fzf-native
    ;;    :repo "dangduc/fzf-native"
    ;;    :host github
    ;;    :files (:defaults "bin"))
    ;;   :config
    ;;   (setq fussy-score-fn 'fussy-fzf-native-score)
    ;;   (fzf-native-load-dyn))

    ;; (use-package hotfuzz
    ;;   :config
    ;;   (setq fussy-score-fn 'fussy-hotfuzz-score))

    (use-package fussy
      :straight (fussy :type git :host github :repo "jojojames/fussy")
      :custom
      (fussy-use-cache t)
      (fussy-compare-same-score-fn 'fussy-histlen->strlen<)

      ;; For example, project-find-file uses 'project-files which uses
      ;; substring completion by default. Set to nil to make sure it's using
      ;; flx.
      (completion-category-defaults nil)
      (completion-category-overrides nil)
      :config
      (setq fussy-filter-fn 'fussy-filter-orderless-flex)
      (push 'fussy completion-styles)

      ;; `eglot' defaults to flex, so set an override to point to fussy instead.
      (with-eval-after-load 'eglot
        (add-to-list 'completion-category-overrides
                     '(eglot (styles fussy basic)))))
  #+end_src
