#+TITLE: Workspace Configuration
#+AUTHOR: Chris Chambers
#+EMAIL: magma.chambers@gmail.com
#+LANGUAGE: en-gb
#+startup: align shrink inlineimages latexpreview content
#+property: header-args:elisp :results value silent

* Enable lexical binding
  #+begin_src elisp
    ;; -*- lexical-binding: t -*-
  #+end_src

* COMMENT Better defaults for window management?
  See: https://github.com/nex3/perspective-el#some-musings-on-emacs-window-layouts

  #+begin_src elisp
    (customize-set-variable
     'display-buffer-base-action
     '((display-buffer-reuse-window display-buffer-same-window)
       (reusable-frames . t)))

    (customize-set-variable 'even-window-sizes nil)     ; avoid resizing
  #+end_src

  #+begin_quote
  These settings do the following:

    - Tell display-buffer to reuse existing windows as much as possible,
      including in other frames. For example, if there is already a *compilation*
      buffer in a visible window, switch to that window. This means that Emacs
      will usually switch windows in a "do what I mean" manner for a warmed-up
      workflow (one with, say, a couple of source windows, a compilation output
      window, and a Magit window).
    - Prevent splits by telling display-buffer to switch to the target buffer in
      the current window. For example, if there is no *compilation* buffer
      visible, then the buffer in whichever window was current when compile was
      run will be replaced with *compilation*. This may seem intrusive, since it
      changes out the current buffer, but keep in mind that most buffers popped
      up in this manner are easy to dismiss, either with a dedicated keybinding
      (often q) or the universally-applicable kill-buffer. This is easier than
      restoring window arrangements. It is also easier to handle for
      pre-arranged window layouts, since the appropriate command can simply be
      run in a window prepared for it in advance. (If this is a step too far,
      then replace display-buffer-same-window with
      display-buffer-pop-up-window.)
  #+end_quote

* COMMENT <<<persp-mode>>>: Frames with specific buffers ([[https://github.com/Bad-ptr/persp-mode.el][github]])
  #+begin_src elisp
    (use-package persp-mode
      :preface
      (defun kill-other-buffers ()
        "Kill all other buffers /in current perspective/."
        (interactive)
        (persp-kill-buffer
              (delq (current-buffer)
                    (org-remove-if-not 'buffer-file-name (persp-buffer-list)))))
      ;; :custom
      ;; (persp-mode-prefix-key (kbd "C-x x"))
      :init
      (persp-mode 1)
      ;; :config
      ;; (with-eval-after-load 'consult
      ;;   (consult-customize consult--source-buffer :hidden t :default nil)
      ;;   (add-to-list 'consult-buffer-sources persp-consult-source))

      ;; :custom
      ;; (persp-init-new-frame-behaviour-override t)
      ;; (persp-emacsclient-init-frame-behaviour-override t)
      :general
      (leader
        ;; Workspace operations
        "TAB"   '(:ignore t :which-key "workspaces")
        "TAB s" '(persp-frame-switch :which-key "switch")
        ;; "TAB S" '(persp-window-switch :which-key "switch (just for window)")
        "TAB b" '(:ignore t :which-key "buffer")
        "TAB ba" '(persp-add-buffer :which-key "add")
        "TAB br" '(persp-remove-buffer :which-key "remove")

        "TAB n" '(persp-next :which-key "next")
        "TAB p" '(persp-prev :which-key "prev")

        "TAB d" '(persp-kill :which-key "delete")
        "TAB r" '(persp-rename :which-key "rename")

        ;; The following line is overridden by consult, if active, but is here as a
        ;; fallback:
        "bb" '(persp-switch-to-buffer :which-key "switch buffer")
        ;; Override kill-other-buffers
        "bo" '(kill-other-buffers :which-key "only this buffer")))
  #+end_src

** COMMENT projectile integration
  #+begin_src elisp
    (use-package persp-mode-projectile-bridge
      :config
      (with-eval-after-load 'projectile
        (add-hook
         'persp-mode-projectile-bridge-mode-hook
         #'(lambda ()
             (if persp-mode-projectile-bridge-mode
                 (persp-mode-projectile-bridge-find-perspectives-for-all-buffers)
               (persp-mode-projectile-bridge-kill-perspectives))))
        (add-hook 'after-init-hook #'(lambda () (persp-mode-projectile-bridge-mode 1)) t)))
  #+end_src

** Fix =evil-alternate-buffer= to work only for current workspace
  #+begin_src elisp
    (defun +workspaces--evil-alternate-buffer-a (&optional window)
      "Make `evil-alternate-buffer' ignore buffers outside the current workspace."
      (let* ((prev-buffers
              (if persp-mode
                  (cl-remove-if-not #'persp-contain-buffer-p (window-prev-buffers)
                                    :key #'car)
                (window-prev-buffers)))
             (head (car prev-buffers)))
        (if (eq (car head) (window-buffer window))
            (cadr prev-buffers)
          head)))

    (advice-add #'evil-alternate-buffer
                :override
                #'+workspaces--evil-alternate-buffer-a)
  #+end_src

* workgroups2 ([[https://github.com/pashinin/workgroups2][github]])
  #+begin_src elisp
    (use-package workgroups2
      :config
      (require 'workgroups2)
      (setq wg-session-file (concat no-littering-var-directory "workgroups"))
      :general
      (leader
        ;; Workspace operations
        "TAB"   '(:ignore t :which-key "workspaces")
        "TAB s" '(wg-create-workgroup :which-key "save")
        "TAB o" '(wg-open-workgroup :which-key "open")
        "TAB d" '(wg-kill-workgroup :which-key "delete")))
  #+end_src
