#+TITLE: Workspace Configuration
#+AUTHOR: Chris Chambers
#+EMAIL: magma.chambers@gmail.com
#+LANGUAGE: en-gb
#+startup: align shrink inlineimages latexpreview content
#+property: header-args:elisp :results value silent

* Enable lexical binding
  #+begin_src elisp
    ;; -*- lexical-binding: t -*-
  #+end_src

* Better defaults for window management?
  See: https://github.com/nex3/perspective-el#some-musings-on-emacs-window-layouts

  #+begin_src elisp
    (customize-set-variable
     'display-buffer-base-action
     '((display-buffer-reuse-window display-buffer-same-window)
       (reusable-frames . t)))

    (customize-set-variable 'even-window-sizes nil)     ; avoid resizing
  #+end_src

  #+begin_quote
  These settings do the following:

    - Tell display-buffer to reuse existing windows as much as possible,
      including in other frames. For example, if there is already a *compilation*
      buffer in a visible window, switch to that window. This means that Emacs
      will usually switch windows in a "do what I mean" manner for a warmed-up
      workflow (one with, say, a couple of source windows, a compilation output
      window, and a Magit window).
    - Prevent splits by telling display-buffer to switch to the target buffer in
      the current window. For example, if there is no *compilation* buffer
      visible, then the buffer in whichever window was current when compile was
      run will be replaced with *compilation*. This may seem intrusive, since it
      changes out the current buffer, but keep in mind that most buffers popped
      up in this manner are easy to dismiss, either with a dedicated keybinding
      (often q) or the universally-applicable kill-buffer. This is easier than
      restoring window arrangements. It is also easier to handle for
      pre-arranged window layouts, since the appropriate command can simply be
      run in a window prepared for it in advance. (If this is a step too far,
      then replace display-buffer-same-window with
      display-buffer-pop-up-window.)
  #+end_quote

* COMMENT <<<persp-mode>>>: Frames with specific buffers ([[https://github.com/Bad-ptr/persp-mode.el][github]])
  #+begin_src elisp
    (use-package persp-mode
      :preface
      (defun kill-other-buffers ()
        "Kill all other buffers /in current perspective/."
        (interactive)
        (persp-kill-buffer
              (delq (current-buffer)
                    (org-remove-if-not 'buffer-file-name (persp-buffer-list)))))
      ;; :custom
      ;; (persp-mode-prefix-key (kbd "C-x x"))
      :init
      (persp-mode 1)
      ;; :config
      ;; (with-eval-after-load 'consult
      ;;   (consult-customize consult--source-buffer :hidden t :default nil)
      ;;   (add-to-list 'consult-buffer-sources persp-consult-source))

      ;; :custom
      ;; (persp-init-new-frame-behaviour-override t)
      ;; (persp-emacsclient-init-frame-behaviour-override t)
      :general
      (leader
        ;; Workspace operations
        "TAB"   '(:ignore t :which-key "workspaces")
        "TAB s" '(persp-frame-switch :which-key "switch")
        ;; "TAB S" '(persp-window-switch :which-key "switch (just for window)")
        "TAB b" '(:ignore t :which-key "buffer")
        "TAB ba" '(persp-add-buffer :which-key "add")
        "TAB br" '(persp-remove-buffer :which-key "remove")

        "TAB n" '(persp-next :which-key "next")
        "TAB p" '(persp-prev :which-key "prev")

        "TAB d" '(persp-kill :which-key "delete")
        "TAB r" '(persp-rename :which-key "rename")

        ;; The following line is overridden by consult, if active, but is here as a
        ;; fallback:
        "bb" '(persp-switch-to-buffer :which-key "switch buffer")
        ;; Override kill-other-buffers
        "bo" '(kill-other-buffers :which-key "only this buffer")))
  #+end_src

** COMMENT projectile integration
  #+begin_src elisp
    (use-package persp-mode-projectile-bridge
      :config
      (with-eval-after-load 'projectile
        (add-hook
         'persp-mode-projectile-bridge-mode-hook
         #'(lambda ()
             (if persp-mode-projectile-bridge-mode
                 (persp-mode-projectile-bridge-find-perspectives-for-all-buffers)
               (persp-mode-projectile-bridge-kill-perspectives))))
        (add-hook 'after-init-hook #'(lambda () (persp-mode-projectile-bridge-mode 1)) t)))
  #+end_src

** Fix =evil-alternate-buffer= to work only for current workspace
  #+begin_src elisp
    (defun +workspaces--evil-alternate-buffer-a (&optional window)
      "Make `evil-alternate-buffer' ignore buffers outside the current workspace."
      (let* ((prev-buffers
              (if persp-mode
                  (cl-remove-if-not #'persp-contain-buffer-p (window-prev-buffers)
                                    :key #'car)
                (window-prev-buffers)))
             (head (car prev-buffers)))
        (if (eq (car head) (window-buffer window))
            (cadr prev-buffers)
          head)))

    (advice-add #'evil-alternate-buffer
                :override
                #'+workspaces--evil-alternate-buffer-a)
  #+end_src

* COMMENT workgroups2 ([[https://github.com/pashinin/workgroups2][github]])
  #+begin_src elisp
    (use-package workgroups2
      :config
      (require 'workgroups2)
      (setq wg-session-file (concat no-littering-var-directory "workgroups"))
      :general
      (leader
        ;; Workspace operations
        "TAB"   '(:ignore t :which-key "workspaces")
        "TAB s" '(wg-create-workgroup :which-key "save")
        "TAB o" '(wg-open-workgroup :which-key "open")
        "TAB d" '(wg-kill-workgroup :which-key "delete")))
  #+end_src

* COMMENT Tabspaces
#+begin_src elisp
  (use-package tabspaces
    :straight (:type git :host github :repo "mclear-tools/tabspaces")
    :hook (after-init . tabspaces-mode)
    :commands (tabspaces-switch-or-create-workspace
               tabspaces-open-or-create-project-and-workspace)
    :custom
    (tabspaces-use-filtered-buffers-as-default t)
    (tabspaces-default-tab "Default")
    (tabspaces-remove-to-default t)
    (tabspaces-include-buffers '("*scratch*"))
    (tabspaces-initialize-project-with-todo t)
    (tabspaces-todo-file-name "project-todo.org")
    ;; sessions
    (tabspaces-session t)
    (tabspaces-session-auto-restore t))

#+end_src
** Filter by workspace when using `consult-Buffer`
   #+begin_src elisp
     (with-eval-after-load 'consult
       ;; hide full buffer list (still available with "b" prefix)
       (consult-customize consult--source-buffer :hidden t :default nil)
       ;; set consult-workspace buffer list
       (defvar consult--source-workspace
         (list :name     "Workspace Buffers"
               :narrow   ?w
               :history  'buffer-name-history
               :category 'buffer
               :state    #'consult--buffer-state
               :default  t
               :items    (lambda () (consult--buffer-query
                                :predicate #'tabspaces--local-buffer-p
                                :sort 'visibility
                                :as #'buffer-name)))

         "Set workspace buffer list for consult-buffer.")
       (add-to-list 'consult-buffer-sources 'consult--source-workspace))

   #+end_src
* <<<Beframe>>> ([[https://github.com/protesilaos/beframe][github]]/[[https://protesilaos.com/emacs/beframe][manual]])
  #+begin_src elisp
    (use-package beframe
      :preface
      (defun my/infer-frame-name (frame name)
        (when-let (((frame-list))
                 (buffer (car (frame-parameter frame 'buffer-list)))
                 (file-name (when (bufferp buffer) (buffer-file-name buffer)))
                 (buf-name (buffer-name buffer))
                 (dir (with-current-buffer buffer (or (vc-root-dir) default-directory))))
          (format "Ɛ: <%s>" (or projectile-project-name
                                (projectile-project-name dir)))))

      (defun my/switch-project-new-frame (dir)
        "\"Switch\" to another project by running an Emacs command.
    The available commands are presented as a dispatch menu
    made from `project-switch-commands'.

    When called in a program, it will use the project corresponding
    to directory DIR."
      (interactive (list (funcall project-prompter)))
      (project-switch-project dir))

      (defun my/rename-frame (frame &optional name)
        (interactive
         (let ((select-frame (beframe--frame-prompt :force-even-if-one)))
           (list
            (beframe--frame-object select-frame)
            (when current-prefix-arg
              (read-string
               (format "Rename the frame now called `%s' to: "
                       select-frame)
               nil 'beframe--rename-frame-history select-frame)))))

        (modify-frame-parameters
         frame
         (list (cons 'name (my/infer-frame-name frame name)))))

      :hook
      (after-init . (lambda () (require 'beframe)))
      :custom
      (beframe-rename-function #'my/rename-frame)
      (beframe-functions-in-frames '(my/switch-project-new-frame))
      :config
      (beframe-mode 1)

      (customize-set-variable
      'beframe-global-buffers
       (-concat beframe-global-buffers
                '("Async-native-compile-log"
                  "\\*Warnings\\*"
                  "\\*Help\\*"
                  "\\*info\\*")))
      :general
      (leader
        "TAB"   '(:ignore t :which-key "workspaces")
        "TAB n" '(ns-next-frame :which-key "next")
        "TAB p" '(ns-prev-frame :which-key "prev")
        "TAB q" '(delete-frame :which-key "quit")

        "pP" '(my/switch-project-new-frame :which-key "switch (new frame)")))
  #+end_src
** =consult-buffer= with =beframe=
   Stolen from: [[https://protesilaos.com/emacs/beframe][Beframe (beframe.el) | Protesilaos Stavrou]]
   #+begin_src elisp
     (with-eval-after-load 'beframe
       (defvar consult-buffer-sources)
       (declare-function consult--buffer-state "consult")

       (with-eval-after-load 'consult
         ;; (consult-customize consult--source-buffer :hidden t :default nil)

         (defface beframe-buffer
           '((t :inherit font-lock-string-face))
           "Face for `consult' framed buffers.")

         (defun my/beframe-buffer-names-sorted (&optional frame)
           "Return the list of buffers from `beframe-buffer-names' sorted by visibility.
     With optional argument FRAME, return the list of buffers of FRAME."
           (beframe-buffer-names frame :sort #'beframe-buffer-sort-visibility))

         (defvar beframe-consult-source
           `( :name     "Frame-specific buffers (current frame)"
              :narrow   ?F
              :category buffer
              :face     beframe-buffer
              :history  beframe-history
              :items    ,#'my/beframe-buffer-names-sorted
              :action   ,#'switch-to-buffer
              :state    ,#'consult--buffer-state))
         ;; (add-to-list 'consult-buffer-sources 'beframe-consult-source)
         (defun my/consult-buffer ()
           (interactive)
           (let* ((consult--source-buffer (plist-put consult--source-buffer :hidden t))
                  (consult--source-buffer (plist-put consult--source-buffer :default nil))
                  (consult-buffer-sources (add-to-list 'consult-buffer-sources
                                                       'beframe-consult-source)))
             (consult-buffer)))))
   #+end_src
